// frontend/app/login/page.tsx
"use client";
import { useAuth } from "../../lib/auth-context";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const { login } = useAuth()
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const router = useRouter()

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)
    setLoading(true)
    try {
      await login(email, password)
      router.push("/cultivos")
    } catch (err: any) {
      setError(err.message || 'Error al iniciar sesión')
    } finally {
      setLoading(false)
    }
  }

  return (
    <main className="px-4 py-10 mx-auto max-w-md">
      <h1 className="text-2xl font-semibold mb-6">Iniciar sesión</h1>
      <form onSubmit={onSubmit} className="space-y-4">
        <div>
          <label className="block text-sm mb-1">Email</label>
          <input type="email" className="w-full border rounded px-3 py-2" value={email} onChange={e=>setEmail(e.target.value)} required />
        </div>
        <div>
          <label className="block text-sm mb-1">Contraseña</label>
          <input type="password" className="w-full border rounded px-3 py-2" value={password} onChange={e=>setPassword(e.target.value)} required />
        </div>
        {error && <p className="text-sm text-red-600">{error}</p>}
        <button disabled={loading} className="bg-green-700 text-white px-4 py-2 rounded disabled:opacity-50">
          {loading ? 'Ingresando…' : 'Entrar'}
        </button>
      </form>
    </main>
  )
}

// frontend-agrotech/src/views/Login.vue
<template>
  <div class="max-w-md mx-auto mt-10 glass p-6">
    <h2 class="text-xl font-semibold mb-4">Login</h2>
    <form @submit.prevent="submit" class="space-y-3">
      <input v-model="email" placeholder="Email" class="w-full px-3 py-2 rounded bg-white/10 outline-none" />
      <input v-model="password" placeholder="Password" type="password" class="w-full px-3 py-2 rounded bg-white/10 outline-none" />
      <button class="px-4 py-2 rounded-lg bg-emerald-500/80 hover:bg-emerald-400/80 transition">Entrar</button>
    </form>
  </div>
  
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const email = ref('')
const password = ref('')
const router = useRouter()
const auth = useAuthStore()

async function submit() {
  try {
    const { supabase } = await import('../services/supabase')
    if (supabase) {
      const { data, error } = await supabase.auth.signInWithPassword({ email: email.value, password: password.value })
      if (error) throw error
    if (data.session) { return router.push('/') }
    }
  } catch (e) {}
  alert('Configura VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY para usar login.')
}
</script>
